language: node_js
node_js:
  - '13'
dist: trusty
addons:
  chrome: stable
  apt:
    packages:
      # - libnss3
notifications:
  email: false
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 & # http://localhost
  # - 'sysctl kernel.unprivileged_userns_clone=1'
  # - 'export DISPLAY=:99.0'
  # - 'sh -e /etc/init.d/xvfb start'
services:
  - mongodb
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
