language: node_js
node_js:
- '13'
dist: trusty
addons:
  chrome: stable
deploy:
  provider: heroku
  api_key:
    secure: VRPqQfT8KFnw1Y3DHHPdDYcZsII2bbVWCatbRMpT8HyBYJmGJWfhzkwUkejPplYIa6gdKbwtM24Rh9UilG9cgi6IFoez46kggV2g8DYuzk26wdkigY1ILGqBlPpGvBMwnifowZk8tv3Nni3Zm8cY0kAQNdQkjRGyp0VVtNoCQRDDanGnFU7Q5q0B4vOVd54lbuCvstll4GbmP8ax6FYK2i86YYSxlB6QuBSquftZM1ZR1AmTtgtwHYUsk9SqApP923Ue+3yTIf5JiKP11WQBr+mBSh+jKzFCQb7tLcJriU1e4cuTTLRcLw5jA++YbPE/BvlAcQGhUWYwhraz9i1WcpWdKHifNdp1iBi3YcpTz4mKjUDC/X9sRB5ufrxAl7NrHrVF8yNmAUmIEmmqZY2Buvrlw7eu3WqFRqIE0843U57Op1pkuqtT9W/zr7wMQFeA3RFlvR1eja30r0u+MuQ6TyyFqIL479rprQ9NiabGpaWn3GQm5HhPCiMxnXmW3YaEw8pyKippQERBJsin9K6HMRLKHU2tfhjHOLZTgSvkiybzlmXtRkNVYwucAe9o6Uu/M7m4K06qugORFWwusaFChuCrHTbimAi7l5yodE0j2TjkcvoOAVl4tnjQRPZ95/i5QXyBKS8PCywnCVzNo9WVNYS3006xsODuTphRu7m927g=
  app: blog-practice-sophie
notifications:
  email: false
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 &
services:
- mongodb
env:
- NODE_ENV=ci PORT=3000
cache:
  directories:
  - node_modules
  - client/node_modules
install:
- npm install
- npm run build
script:
- nohup npm run start &
- sleep 3
- npm run test
